apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: secure-ai-gateway
resources:
  - ../base
  - ../migration
  - serviceaccounts.yaml
  - observability.yaml
patches:
  - path: gateway-patch.yaml
  - path: migration-patch.yaml
  - path: delete-generated-configmaps.yaml
