apiVersion: v1
kind: ServiceAccount
metadata:
  name: sag-gateway
  namespace: secure-ai-gateway
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sag-migration
  namespace: secure-ai-gateway
automountServiceAccountToken: false
